import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

/**
 * ⚠️ AN EXTERNAL CONSUMER REPLICATES THIS FILE. READ BEFORE EDITING.
 *
 * hydra-recall's crystallisation regression gate replicates `l2normalize`
 * below **byte for byte** rather than reimplementing it, deliberately —
 * "equivalent" is not equivalent at 5.7e-10 sensitivity. Changing its
 * arithmetic silently changes what that gate measures, and their suite will
 * stay green while measuring something else.
 *
 * A change here needs a message to hydra-claude, not just a passing local
 * suite. Same for `FIXTURE_SHA256` and the synthetic-row filter, since
 * hydra-recall runs against the same corpus.
 *
 * Also: the figures this file feeds are **regime x backend, a 2x2** — not a
 * regime-indexed pair. Quoting one without naming BOTH axes has already
 * caused a wrong expectation to be written into a downstream spec (native x
 * normalised, 34 / 27.2%, cited where wasm x normalised, 36 / 27.0%, was
 * meant — two clusters out). Name both axes, always.
 */

/**
 * sha256 of the reference corpus, pinned by CONTENT rather than by shape.
 *
 * The corpus lives outside this repository and **nothing versions it**. It is
 * a shared dependency of holomap, coda and hydra-recall with no owner, which
 * is exactly how a file ends up regenerated by someone solving an unrelated
 * problem. If that happened, every figure here would move and nothing would
 * notice — the row-count and dimensionality checks pass for any 723x1024
 * export, not only for this one.
 *
 * A green gate silently measuring a different corpus is worse than a red one.
 * Kept in sync by hand with `FIXTURE_SHA256` in
 * `crates/holomap-clusterer/tests/fixture_regression.rs`.
 */
export const FIXTURE_SHA256 = 'd65077b8c3f62fa2a873507cacc8a7afb8f46ad9ad7e7b959bc23591f9620c4b';

/**
 * Reference-corpus loader, mirroring `load_fixture` in
 * `crates/holomap-clusterer/tests/fixture_regression.rs`.
 *
 * Env-gated on `HOLOMAP_CLUSTERER_FIXTURE` for the same reason the Rust side
 * is: the corpus is 9.4 MB and lives outside this repo. Unset, callers skip.
 *
 * The TSV has 6 tab-separated columns; col 5 (index 4) is the text, used to
 * exclude the 76 synthetic perf fixtures, and col 6 (index 5) is a JSON array
 * of 1024 bge-m3 floats.
 *
 * The synthetic-row exclusion is not optional and not a detail. Coda's MVD §5
 * found those near-duplicates form the densest regions in the whole corpus and
 * dominate a naive clustering — they have to go before the clusterer sees the
 * data. The two filter prefixes are duplicated from the Rust loader by hand;
 * if either side changes, `expectedRows` below stops matching and the caller
 * fails loudly rather than silently clustering a different corpus.
 */
export const FIXTURE_ROWS = 723;
export const FIXTURE_DIMS = 1024;

export function fixturePath(): string | undefined {
  return process.env.HOLOMAP_CLUSTERER_FIXTURE;
}

export function loadFixture(path: string): Float32Array[] {
  const raw = readFileSync(path, 'utf8');

  const digest = createHash('sha256').update(raw).digest('hex');
  if (digest !== FIXTURE_SHA256) {
    throw new Error(
      `reference corpus at ${path} is NOT the file these figures were measured against.\n` +
        `  expected sha256 ${FIXTURE_SHA256}\n` +
        `  actual   sha256 ${digest}\n` +
        `Every number in this suite is specific to that exact export. If the corpus was ` +
        `legitimately regenerated, re-measure and update both this constant and the matching ` +
        `one in crates/holomap-clusterer/tests/fixture_regression.rs — do not just widen the bands.`
    );
  }

  const out: Float32Array[] = [];
  for (const line of raw.split('\n')) {
    const cols = line.split('\t');
    if (cols.length < 6) continue;
    const text = cols[4]!;
    if (text.startsWith('Seed session ') || text.startsWith('perf-seed-memory-')) continue;

    const raw = cols[5]!.trim().replace(/^\[|\]$/g, '');
    const parts = raw.split(',');
    const v = new Float32Array(parts.length);
    // Float32Array assignment does the f64 -> f32 rounding, matching what the
    // Rust loader's `parse::<f32>()` produces for the same decimal text.
    for (let i = 0; i < parts.length; i++) v[i] = Number(parts[i]);
    out.push(v);
  }

  if (out.length !== FIXTURE_ROWS) {
    throw new Error(
      `fixture has ${out.length} rows after filtering, expected ${FIXTURE_ROWS} — ` +
        `the synthetic-row filter is out of sync with the Rust loader, or this is a different export`
    );
  }
  if (out[0]!.length !== FIXTURE_DIMS) {
    throw new Error(`fixture is ${out[0]!.length}-dimensional, expected ${FIXTURE_DIMS}`);
  }
  return out;
}

/**
 * L2-normalise the way a JavaScript consumer does without deciding to.
 *
 * Every JS number is a double, so `sum` accumulates in f64 over the f32
 * values and only re-rounds on store. That is the `normalised/f64` regime in
 * the Rust suite, and it is what coda's production `l2normalize` produces —
 * confirmed by coda reproducing 34 clusters / 27.2% once it replicated its
 * own function literally instead of paraphrasing it.
 *
 * Do NOT "simplify" this to operate on the pre-cast values. That change is
 * what produced a wrong number once already, and it looks like a cleanup.
 */
export function l2normalize(vectors: readonly Float32Array[]): Float32Array[] {
  return vectors.map((v) => {
    let sum = 0;
    for (const x of v) sum += x * x;
    const norm = Math.sqrt(sum);
    if (norm === 0) return new Float32Array(v);
    const out = new Float32Array(v.length);
    for (let i = 0; i < v.length; i++) out[i] = v[i]! / norm;
    return out;
  });
}

export function clusterCount(assignments: readonly number[]): number {
  return new Set(assignments.filter((l) => l >= 0)).size;
}

export function noiseCount(assignments: readonly number[]): number {
  return assignments.filter((l) => l === -1).length;
}
