//! Reference-corpus regression gate.
//!
//! The unit suite proves the code is wired correctly. This proves the
//! PIPELINE still behaves, across the input regimes that actually occur.
//!
//! # Three regimes, because "normalised" is not one thing
//!
//! This crate's baseline of 36 clusters / 30.0% noise is measured on RAW
//! corpus floats — the TSV parsed and fed straight in.
//!
//! No TypeScript consumer feeds that. Raw bge-m3 vectors are not unit
//! length (norm ~25), and consumers L2-normalise at their own boundary so
//! cosine can be computed as a plain dot product downstream.
//!
//! [`holomap_clusterer::pipeline::run_pipeline`] L2-normalises internally as
//! step 1, so pre-normalising is **mathematically a no-op**. It is not a
//! no-op in practice, and — this is the part that surprised us — it does not
//! even have a single answer. Measured 2026-08-05 on the 723-row corpus at
//! the pinned params:
//!
//! | input | clusters | noise |
//! |---|---|---|
//! | raw | 36 | 30.0% (217 rows) |
//! | normalised, norm accumulated in f32 | 37 | 29.2% (211 rows) |
//! | normalised, norm accumulated in f64 | 34 | 27.2% (197 rows) |
//!
//! All three are the same vectors to within float32 rounding. The spread is
//! 3 clusters and 20 noise rows, produced entirely by *how* the division was
//! rounded. A fourth path — coda's `EmbeddingsGateway`, which normalises in
//! its own way — reported 33 / 25.4%, which neither variant here reproduces.
//!
//! **The 27.2% in the f64 row is a coincidence.** sklearn's figure for this
//! corpus is also 27.2% (via coda's `holomap_gate.py`, which reduces with
//! holomap but clusters with sklearn). They are unrelated numbers that
//! happen to collide, and reading this as the two pipelines converging would
//! be wrong. See `pipeline.rs`'s module doc for that attribution.
//!
//! # Deterministic is not the same as numerically stable
//!
//! Identical input reproduces identical output — that contract holds, it is
//! verified elsewhere, and it is the product. It does not imply that
//! *near*-identical input produces near-identical output, and here it does
//! not: HDBSCAN is a density algorithm, so a perturbation far below any
//! meaningful precision moves points across cluster boundaries, and the
//! effect compounds through the reduction.
//!
//! What this suite can honestly gate is therefore the MVD's band, applied to
//! every regime — not an exact count in any one of them. An equality
//! assertion here would pin one arbitrary point of a sensitive function and
//! call it a contract. The useful guarantee is that whichever of these a
//! consumer feeds, the result stays inside the envelope the consumer's
//! design requires.
//!
//! # Running it
//!
//! Env-gated because the fixture is 9.4 MB and lives outside this repo: a
//! 799-row TSV export of the Claude corpus described in coda's MVD (6
//! tab-separated columns; col 5 is the text, used to exclude the 76
//! synthetic perf fixtures; col 6 is a JSON array of 1024 bge-m3 floats).
//! Point HOLOMAP_CLUSTERER_FIXTURE at your local copy of that export;
//! unset it and this skips, exactly like hydra's POSTGRES_URL-gated
//! suites:
//!
//!   HOLOMAP_CLUSTERER_FIXTURE=/path/to/2026-06-05-claude-corpus-799.tsv \
//!     cargo test -p holomap-clusterer --test fixture_regression -- --nocapture

use holomap_clusterer::pipeline::run_pipeline;
use holomap_clusterer::protocol::{Params, Request, PROTOCOL_VERSION};
use sha2::{Digest, Sha256};

/// sha256 of the reference corpus, pinned by CONTENT rather than by shape.
///
/// The corpus lives outside this repository and **nothing versions it**. It is
/// a shared dependency of holomap, coda and hydra-recall with no owner, which
/// is exactly how a file ends up regenerated by someone solving an unrelated
/// problem. If that happened, every figure in this suite would move and
/// nothing here would notice — the row-count and dimensionality checks below
/// pass for any 723x1024 export, not only for this one.
///
/// A green gate silently measuring a different corpus is worse than a red one.
const FIXTURE_SHA256: &str = "d65077b8c3f62fa2a873507cacc8a7afb8f46ad9ad7e7b959bc23591f9620c4b";

/// The MVD's established envelope, applied to every regime.
const CLUSTER_BAND: std::ops::RangeInclusive<usize> = 30..=60;
const NOISE_BAND: std::ops::RangeInclusive<f64> = 10.0..=35.0;

/// Load the corpus, excluding the 76 synthetic perf fixtures. Coda's MVD §5
/// found those near-duplicates form the densest regions in the whole corpus
/// and dominate naive clustering — they must go before the clusterer sees
/// the data, not after.
fn load_fixture(path: &str) -> Vec<Vec<f32>> {
    let raw = std::fs::read_to_string(path).expect("fixture readable");

    let digest = format!("{:x}", Sha256::digest(raw.as_bytes()));
    assert_eq!(
        digest, FIXTURE_SHA256,
        "\nreference corpus at {path} is NOT the file these figures were measured against.\
         \n  expected sha256 {FIXTURE_SHA256}\
         \n  actual   sha256 {digest}\
         \nEvery number in this suite is specific to that exact export. If the corpus was\
         \nlegitimately regenerated, re-measure and update both this constant and the\
         \nmatching one in npm/test/fixture.ts — do not just widen the bands.\n"
    );

    raw.lines()
        .filter_map(|line| {
            let cols: Vec<&str> = line.split('\t').collect();
            if cols.len() < 6 {
                return None;
            }
            if cols[4].starts_with("Seed session ") || cols[4].starts_with("perf-seed-memory-") {
                return None;
            }
            let vec: Vec<f32> = cols[5]
                .trim_matches(['[', ']'].as_ref())
                .split(',')
                .map(|x| x.trim().parse::<f32>().expect("float"))
                .collect();
            Some(vec)
        })
        .collect()
}

/// L2-normalise accumulating the norm in f32.
///
/// Matches what `pipeline.rs` itself does internally, so this is the variant
/// that is closest to "the same operation applied twice".
fn l2_normalise_f32(vecs: &[Vec<f32>]) -> Vec<Vec<f32>> {
    vecs.iter()
        .map(|v| {
            let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
            if norm == 0.0 {
                v.clone()
            } else {
                v.iter().map(|x| x / norm).collect()
            }
        })
        .collect()
}

/// L2-normalise accumulating the norm in f64, then round back to f32.
///
/// This is what a JavaScript consumer produces without meaning to: every JS
/// number is a double, so normalising a `Float32Array` in JS does the
/// arithmetic in f64 and only re-rounds on store. Included because it is a
/// realistic consumer path, not because it is more correct — the point of
/// having both is that the choice is invisible at the call site and still
/// changes the answer.
fn l2_normalise_f64(vecs: &[Vec<f32>]) -> Vec<Vec<f32>> {
    vecs.iter()
        .map(|v| {
            let norm: f64 = v
                .iter()
                .map(|&x| f64::from(x) * f64::from(x))
                .sum::<f64>()
                .sqrt();
            if norm == 0.0 {
                v.clone()
            } else {
                v.iter().map(|&x| (f64::from(x) / norm) as f32).collect()
            }
        })
        .collect()
}

/// Run the pipeline and return (cluster count, noise percentage).
fn cluster(vectors: Vec<Vec<f32>>) -> (usize, f64) {
    let resp = run_pipeline(&Request {
        protocol_version: PROTOCOL_VERSION,
        vectors,
        params: Params {
            n_components: 10,
            n_neighbors: 15,
            min_cluster_size: 5,
            seed: 42,
        },
    });
    assert!(resp.error.is_none(), "pipeline errored: {:?}", resp.error);

    let mut labels = resp.assignments.clone();
    labels.sort_unstable();
    labels.dedup();
    let clusters = labels.iter().filter(|&&l| l >= 0).count();
    let noise = resp.assignments.iter().filter(|&&l| l == -1).count();
    let noise_pct = 100.0 * noise as f64 / resp.assignments.len() as f64;
    (clusters, noise_pct)
}

fn assert_in_band(regime: &str, clusters: usize, noise_pct: f64) {
    eprintln!("{regime}: clusters={clusters} noise={noise_pct:.1}%");
    assert!(
        CLUSTER_BAND.contains(&clusters),
        "{regime}: cluster count {clusters} outside the {:?} gate",
        CLUSTER_BAND
    );
    assert!(
        NOISE_BAND.contains(&noise_pct),
        "{regime}: noise {noise_pct:.1}% outside the {:?}% gate",
        NOISE_BAND
    );
}

fn fixture() -> Option<Vec<Vec<f32>>> {
    let path = std::env::var("HOLOMAP_CLUSTERER_FIXTURE").ok()?;
    let vectors = load_fixture(&path);
    assert_eq!(vectors.len(), 723, "expected 799 rows minus 76 synthetic");
    assert_eq!(vectors[0].len(), 1024, "bge-m3 dimensionality");
    Some(vectors)
}

/// Raw, unnormalised input — this crate's own published baseline.
#[test]
fn reference_corpus_raw_input() {
    let Some(vectors) = fixture() else {
        eprintln!("skipping: HOLOMAP_CLUSTERER_FIXTURE unset");
        return;
    };
    let (clusters, noise_pct) = cluster(vectors);
    assert_in_band("raw", clusters, noise_pct);
}

/// Pre-normalised input, f32 accumulation — the variant matching what the
/// pipeline does internally.
///
/// This case exists because coda's integration nearly reported a false
/// regression against the raw baseline: its gateway normalises by contract,
/// so it could not reproduce the published figure and the gap looked like a
/// defect. It is not one. Every regime here is correct; they simply are not
/// the same number.
#[test]
fn reference_corpus_normalised_f32() {
    let Some(vectors) = fixture() else {
        eprintln!("skipping: HOLOMAP_CLUSTERER_FIXTURE unset");
        return;
    };
    let (clusters, noise_pct) = cluster(l2_normalise_f32(&vectors));
    assert_in_band("normalised/f32", clusters, noise_pct);
}

/// Pre-normalised input, f64 accumulation — the JavaScript consumer path.
#[test]
fn reference_corpus_normalised_f64() {
    let Some(vectors) = fixture() else {
        eprintln!("skipping: HOLOMAP_CLUSTERER_FIXTURE unset");
        return;
    };
    let (clusters, noise_pct) = cluster(l2_normalise_f64(&vectors));
    assert_in_band("normalised/f64", clusters, noise_pct);
}

/// The stability characteristic itself, reported as a measurement rather
/// than asserted as a contract.
///
/// All three inputs are the same vectors to within float32 rounding, and
/// pre-normalising is mathematically a no-op against a pipeline that
/// normalises internally. This prints how far apart they land anyway.
///
/// It asserts only that every regime stays in band — deliberately NOT that
/// they diverge, and not any particular spread. A future holomap that
/// narrowed this gap would be an improvement and must not fail a test for
/// it. The printed table is the artifact worth reading; if you are here
/// because a number moved, compare the whole table rather than one row.
#[test]
fn normalisation_is_a_no_op_that_still_moves_the_result() {
    let Some(vectors) = fixture() else {
        eprintln!("skipping: HOLOMAP_CLUSTERER_FIXTURE unset");
        return;
    };
    let regimes = [
        ("raw", cluster(vectors.clone())),
        ("normalised/f32", cluster(l2_normalise_f32(&vectors))),
        ("normalised/f64", cluster(l2_normalise_f64(&vectors))),
    ];

    let counts: Vec<usize> = regimes.iter().map(|(_, (c, _))| *c).collect();
    let noises: Vec<f64> = regimes.iter().map(|(_, (_, n))| *n).collect();
    eprintln!(
        "spread across mathematically-equivalent inputs: {} clusters, {:.1} noise points",
        counts.iter().max().unwrap() - counts.iter().min().unwrap(),
        noises.iter().cloned().fold(f64::MIN, f64::max)
            - noises.iter().cloned().fold(f64::MAX, f64::min)
    );

    for (regime, (clusters, noise_pct)) in regimes {
        assert_in_band(regime, clusters, noise_pct);
    }
}
